# Generated by Django 6.0.3 on 2026-08-05 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0014_alter_session_status_dailycontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycontribution',
            options={'ordering': ['-scheduled_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='dailycontribution',
            name='focusapp_da_user_id_02b05f_idx',
        ),
        migrations.RenameField(
            model_name='dailycontribution',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.AlterField(
            model_name='dailycontribution',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='dailycontribution',
            index=models.Index(fields=['user', 'scheduled_date'], name='focusapp_da_user_id_ac6ca7_idx'),
        ),
    ]
